function k(b,a,c,d,e){b.v.Ab(b.cb,a,c,d,e)}function l(b,a,c,d){b.v.ka?k(b,a,c,d):b.v.ze()._OnMessageFromDOM({type:"event",component:b.cb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.v.C(b.cb,a,c)}function aa(b,a){for(const [c,d]of a)n(b,c,d)}function r(b){b.Lb||(b.v.se(b.Qd),b.Lb=!0)}function ba(b){b.Lb&&(b.v.Ke(b.Qd),b.Lb=!1)}window.lc=class{constructor(b,a){this.v=b;this.cb=a;this.Lb=!1;this.Qd=()=>this.za()}Zc(){}za(){}};
function ca(b){-1!==b.Ta&&(self.clearTimeout(b.Ta),b.Ta=-1)}window.pe=class{constructor(b){this.Ec=b;this.Oe=5;this.Ta=-1;this.Nb=-Infinity;this.Rd=()=>{this.Ta=-1;this.Nb=Date.now();this.ib=!0;this.Ec();this.ib=!1};this.td=this.ib=!1}j(){ca(this);this.Rd=this.Ec=null}};"use strict";
function da(b,a){const c=a.elementId,d=b.cd(c,a);b.W.set(c,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{u(b,"elem-focused",c)});d.addEventListener("blur",()=>{u(b,"elem-blurred",c)});b.ab&&document.body.appendChild(d)}function v(b,a,c){n(b,a,d=>{const e=b.W.get(d.elementId);return c(e,d)})}function u(b,a,c,d){d||(d={});d.elementId=c;k(b,a,d)}
window.ie=class extends self.lc{constructor(b){super(b,"video");this.W=new Map;this.ab=!0;aa(this,[["create",a=>da(this,a)],["destroy",a=>{a=a.elementId;const c=this.W.get(a);this.ed(c);this.ab&&c.parentElement.removeChild(c);this.W.delete(a)}],["set-visible",a=>{this.ab&&(this.W.get(a.elementId).style.display=a.isVisible?"":"none")}],["update-position",a=>{if(this.ab){var c=this.W.get(a.elementId);c.style.left=a.left+"px";c.style.top=a.top+"px";c.style.width=a.width+"px";c.style.height=a.height+
"px";a=a.fontSize;null!==a&&(c.style.fontSize=a+"em")}}],["update-state",a=>{this.W.get(a.elementId);this.hd()}],["focus",a=>{const c=this.W.get(a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{this.W.get(a.elementId).style[a.prop]=a.val}],["set-attribute",a=>{this.W.get(a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{this.W.get(a.elementId).removeAttribute(a.name)}]]);v(this,"get-element",a=>a)}cd(){throw Error("required override");}ed(){}hd(){throw Error("required override");
}};"use strict";const ea=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),w=/android/i.test(navigator.userAgent);let fa=0;function x(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ze?new Promise(c=>{const d="c3_resolve_"+fa;++fa;self[d]=c;a.textContent=b.cf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ha=!1,ia=!1;
function ja(){if(!ha){try{new Worker("blob://",{get type(){ia=!0}})}catch(b){}ha=!0}return ia}let y=new Audio;const ka={"audio/webm; codecs=opus":!!y.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!y.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!y.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!y.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!y.canPlayType("audio/mp4"),"audio/mpeg":!!y.canPlayType("audio/mpeg")};y=null;
async function la(b){b=await ma(b);return(new TextDecoder("utf-8")).decode(b)}function ma(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const z=[];let B=0;window.RealFile=window.File;const C=[],D=new Map,F=new Map;let na=0;const oa=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");oa.push(b)};const pa=new Set(["cordova","playable-ad","instant-games"]);
let qa=!1;
window.Cb=class b{constructor(a){this.ka=a.ef;this.va=null;this.ca="";this.cc=a.bf;this.xb={};this.Ma=this.wb=null;this.Jb=[];this.H=this.Ra=null;this.Nc=!1;this.wd=0;this.kb=null;this.Qa=-1;this.Te=()=>this.Ge();this.Pa=[];this.D=a.Sd;this.Mb="file"===location.protocol.substr(0,4);!this.ka||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ja()||(this.ka=!1);if("playable-ad"===this.D||"instant-games"===this.D)this.ka=!1;if("cordova"===this.D&&this.ka)if(w){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.ka=!1)}else this.ka=!1;this.Qb=this.oa=null;"html5"!==this.D||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.Ce(c));this.C("runtime","create-job-worker",()=>this.De());"cordova"===this.D?document.addEventListener("deviceready",()=>this.ld(a)):this.ld(a)}j(){this.vc();
this.va&&(this.va=this.va.onmessage=null);this.wb&&(this.wb.terminate(),this.wb=null);this.Ma&&(this.Ma.j(),this.Ma=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}me(){return ea&&"cordova"===this.D}rc(){const a=navigator.userAgent;return ea&&pa.has(this.D)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}ke(){return w}qc(){return w&&pa.has(this.D)}async ld(a){"macos-wkwebview"===this.D&&this.Le();if("playable-ad"===this.D){this.oa=self.c3_base64files;this.Qb={};await this.ve();
for(let d=0,e=a.Ua.length;d<e;++d){var c=a.Ua[d].toLowerCase();this.Qb.hasOwnProperty(c)?a.Ua[d]={Ze:!0,cf:this.Qb[c]}:this.oa.hasOwnProperty(c)&&(a.Ua[d]=URL.createObjectURL(this.oa[c]))}}a.af?this.ca=a.af:(c=location.origin,this.ca=("null"===c?"file:///":c)+location.pathname,c=this.ca.lastIndexOf("/"),-1!==c&&(this.ca=this.ca.substr(0,c+1)));a.gf&&(this.xb=a.gf);c=new MessageChannel;this.va=c.port1;this.va.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>
this.Fe(d));this.kb=new self.ne(this);await ra(this.kb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ka?await this.Be(a,c.port2):await this.Ae(a,c.port2)}xc(a){a=this.xb.hasOwnProperty(a)?this.xb[a]:a.endsWith("/workermain.js")&&this.xb.hasOwnProperty("workermain.js")?this.xb["workermain.js"]:
"playable-ad"===this.D&&this.oa.hasOwnProperty(a.toLowerCase())?this.oa[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async kc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.D&&this.Mb)return a=await this.yb(d.Ye?a:this.cc+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}ta(){return Math.max(window.innerWidth,1)}la(){return Math.max(window.innerHeight,1)}kd(a){var c=this.ca,d=location.href,e=this.ta(),f=this.la(),g=window.devicePixelRatio,h=b.Ya(),m=a.mf,p=window.cr_previewImageBlobs||this.oa,q=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,A=window.kf||"";a=a.Sd;var Y=(new URLSearchParams(self.location.search)).has("debug"),E=this.kb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,
isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:t,swClientId:A,exportType:a,isDebug:Y,ife:!!self.lf,jobScheduler:{inputPort:E.Mc,outputPort:E.Tc,maxNumWorkers:E.Qe},supportedAudioFormats:ka,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.cc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.cc+"opus.wasm.wasm",isFileProtocol:this.Mb,isiOSCordova:this.me(),isiOSWebView:this.rc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Be(a,
c){var d=this.xc(a.ff);this.wb=await this.kc(d,this.ca,{type:"module",name:"Runtime",Ye:!0});this.H=document.createElement("canvas");this.H.style.display="none";d=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let e=a.Yc||[],f=a.Ua;e=await Promise.all(e.map(g=>this.Ha(g)));f=await Promise.all(f.map(g=>this.Ha(g)));if("cordova"===this.D)for(let g=0,h=a.hc.length;g<h;++g){const m=a.hc[g],p=
m[0];if(p===a.Wc||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))m[1]=await this.Ha(p)}this.wb.postMessage(Object.assign(this.kd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,workerDependencyScripts:e,engineScripts:f,projectScripts:a.hc,mainProjectScript:a.Wc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...sa(this.kb)]);this.Jb=C.map(g=>new g(this));this.jd();self.c3_callFunction=(g,h)=>{var m=this.Ra;return m.v.gd(m.cb,"js-invoke-function",{name:g,params:h},
void 0,void 0)};"preview"===this.D&&(self.goToLastErrorScript=()=>this.Ab("runtime","go-to-last-error-script"))}async Ae(a,c){this.H=document.createElement("canvas");this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Jb=C.map(g=>new g(this));this.jd();var d=a.Ua.map(g=>"string"===typeof g?(new URL(g,this.ca)).toString():g);Array.isArray(a.Yc)&&d.unshift(...a.Yc);d=await Promise.all(d.map(g=>this.Ha(g)));
await Promise.all(d.map(g=>x(g)));d=self.C3_ProjectScriptsStatus;const e=a.Wc,f=a.hc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ha(h),await x(h),"preview"!==this.D||d[g]||this.nd(g,"main script did not run to completion")}catch(m){this.nd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ha(h),await x(h);"preview"===this.D&&"object"!==typeof self.hf.jf?(this.Fb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.kd(a),{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:oa}),this.md(),this.Ma=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ma,a))}nd(a,c){this.Fb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}md(){this.Fb()}Fb(){const a=
window.We;a&&(a.parentElement.removeChild(a),window.We=null)}async De(){const a=await ta(this.kb);return{outputPort:a,transferables:[a]}}ze(){if(this.ka)throw Error("not available in worker mode");return this.Ma}Ab(a,c,d,e,f){this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}gd(a,c,d,e,f){const g=na++,h=new Promise((m,p)=>{F.set(g,{resolve:m,reject:p})});this.va.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ee(a);if("result"===c)this.He(a);else if("runtime-ready"===c)this.Ie();else if("alert-error"===c)this.Fb(),alert(a.message);else if("creating-runtime"===c)this.md();else throw Error(`unknown message '${c}'`);}Ee(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=D.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Eb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Eb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Eb(f,!1,""+h)}):this.Eb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Eb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.va.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}He(a){const c=a.responseId,d=a.isOk;a=a.result;const e=F.get(c);d?e.resolve(a):e.reject(a);F.delete(c)}C(a,
c,d){let e=D.get(a);e||(e=new Map,D.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static ic(a){if(C.includes(a))throw Error("DOM handler already added");C.push(a)}jd(){for(const a of this.Jb)if("runtime"===a.cb){this.Ra=a;return}throw Error("cannot find runtime DOM handler");}Fe(a){this.Ab("debugger","message",a)}Ie(){for(const a of this.Jb)a.Zc()}static Ya(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
qa)}static od(a){qa=!!a}se(a){this.Pa.push(a);this.Cc()}Ke(a){a=this.Pa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Pa.splice(a,1);this.Pa.length||this.vc()}Cc(){-1===this.Qa&&this.Pa.length&&(this.Qa=requestAnimationFrame(this.Te))}vc(){-1!==this.Qa&&(cancelAnimationFrame(this.Qa),this.Qa=-1)}Ge(){this.Qa=-1;for(const a of this.Pa)a();this.Cc()}ba(a){this.Ra.ba(a)}fa(a){this.Ra.fa(a)}Bc(){this.Ra.Bc()}Db(a){this.Ra.Db(a)}le(){return!!ka["audio/webm; codecs=opus"]}async Me(a){a=await this.gd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}qe(a){this.Nc=!0;this.wd=a}je(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}fd(a){return!this.je(a)}async Ha(a){return"cordova"===this.D&&(a.startsWith("file:")||this.Mb&&this.fd(a))?(a.startsWith(this.ca)&&(a=a.substr(this.ca.length)),a=await this.yb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ce(a){const c=a.filename;switch(a.as){case "text":return await this.he(c);
case "buffer":return await this.yb(c);default:throw Error("unsupported type");}}bd(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async he(a){a=await this.bd(a);return await la(a)}wc(){if(z.length&&!(8<=B)){B++;var a=z.shift();this.we(a.filename,a.df,a.Xe)}}yb(a){return new Promise((c,d)=>{z.push({filename:a,df:e=>{B--;this.wc();c(e)},Xe:e=>{B--;this.wc();d(e)}});this.wc()})}async we(a,
c,d){try{const e=await this.bd(a),f=await ma(e);c(f)}catch(e){d(e)}}Le(){var a={type:"ready"};if("windows-webview2"===this.D)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.D)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ve(){const a=[];for(const [c,d]of Object.entries(this.oa))a.push(this.ue(c,d));await Promise.all(a)}async ue(a,c){if("object"===typeof c)this.oa[a]=new Blob([c.str],
{type:c.type}),this.Qb[a]=c.str;else{let d=await this.ye(c);d||(d=this.xe(c));this.oa[a]=d}}async ye(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}xe(a){a=this.Je(a);return this.te(a.data,a.$e)}Je(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");
var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{$e:a,data:d}}te(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const G=self.Cb;
function ua(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const va=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),H={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},wa={dispatchUserScriptEvent:!0},I={dispatchRuntimeEvent:!0};
function xa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ya(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function J(b){b=URL.createObjectURL(b);try{return await ya(b)}finally{URL.revokeObjectURL(b)}}
function za(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Aa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await J(b);var d=await za(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await J(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await J(b)}
function Ba(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Ca=new Set(["input","textarea","datalist","select"]),Da=new Set(["canvas","body","html"]);function K(b){Da.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ea(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await J(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Aa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Fa=!1;document.addEventListener("pause",()=>Fa=!0);document.addEventListener("resume",()=>Fa=!1);async function Ga(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ha(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ja(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ka(b){self.setTimeout(()=>{b.vd=!0},1E3);"cordova"===b.v.D?(document.addEventListener("pause",()=>La(b,!0)),document.addEventListener("resume",()=>La(b,!1))):document.addEventListener("visibilitychange",()=>La(b,document.hidden));return{isSuspended:!(!document.hidden&&!Fa)}}
function Ma(b){b.qd||(b.qd=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},H)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},H)}))}
function Na(b){b.pd||(b.pd=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},H)}}))}async function Oa(b){await xa(b.url)}
function Pa(b,a){b.xd=a.message;-1===b.Ic&&(b.Ic=setTimeout(()=>{b.Ic=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.xd)},250))}function L(b){if(!b.Z){var a=G.Ya();a&&"any"!==b.Uc&&Qa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ta(),innerHeight:b.la()})}}function Ra(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:G.Ya(),innerWidth:b.ta(),innerHeight:b.la()})}
function La(b,a){a?b.v.vc():b.v.Cc();k(b,"visibilitychange",{hidden:a})}function Sa(b,a,c){"Backspace"===c.key&&K(c);if(!b.Z){var d=va.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},H)}}
function Ta(b,a,c,d){b.Z||ua(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.$,pageX:c.pageX,pageY:c.pageY+b.$,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Ua(b){window!==window.top&&window.focus();Wa(b.target)&&document.activeElement&&!Wa(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.Z){if(b.sb&&"pointermove"!==a){var d=b.sb;d.ib||(ca(d),d.Nb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.pb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.$,pageX:c.pageX,pageY:c.pageY+b.$,movementX:(c.movementX||0)+b.Yb,movementY:(c.movementY||0)+b.Zb,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||
0,twist:c.twist||0,timeStamp:c.timeStamp},H);b.Yb=0;b.Zb=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Ta(b,d,c,wa),b.pb=c.buttons)}}
function Xa(b,a,c){if(!b.Z&&!ua(c)){var d=b.pb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.$,pageX:c.pageX,pageY:c.pageY+b.$,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},H);b.pb=c.buttons;Ta(b,c.type,c,wa)}}
function N(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.$,pageX:f.pageX,pageY:f.pageY+b.$,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
H)}}function Ya(b,a,c){document.body.style.transform="";b.$=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.$=a))}}function Za(b,a,c,d){const e=b.ta(),f=b.la();b.Sa=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.Ya()}):10>d&&$a(b,e,f,d+1)}
function $a(b,a,c,d){-1!==b.Sa&&clearTimeout(b.Sa);b.Sa=setTimeout(()=>Za(b,a,c,d),48)}
function Qa(b){b=b.Uc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Wa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
G.ic(class extends self.lc{constructor(b){super(b,"runtime");this.Cd=!0;this.Sa=-1;this.Uc="any";this.pd=this.qd=!1;this.Ca=null;this.Z=!1;this.xd="";this.Ic=-1;this.La=this.sb=null;this.Zb=this.Yb=0;this.vd=!1;this.Gd=b.ta();this.Ob=b.la();this.$=this.vb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Nc||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",this.Cd&&(e.style.display="",this.Cd=!1))});b.C("runtime",
"invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","raster-svg-image",d=>Ga(d));b.C("runtime","get-svg-image-size",d=>Ha(d));b.C("runtime","set-target-orientation",d=>{this.Uc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ja(d));b.C("runtime","go-to-script",d=>
Ja(d));b.C("runtime","before-start-ticking",()=>Ka(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ca||(this.Ca=document.createElement("div"),this.Ca.id="inspectOutline",document.body.appendChild(this.Ca));var e=this.Ca;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ca&&(this.Ca.style.display="none")});b.C("runtime","enable-device-orientation",()=>Ma(this));b.C("runtime","enable-device-motion",
()=>Na(this));b.C("runtime","add-stylesheet",d=>Oa(d));b.C("runtime","alert",d=>{alert(d.message)});b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.H.style.display="";this.v.qe(d.duration)});b.C("runtime",
"export-to-video-progress",d=>Pa(this,d));b.C("runtime","exported-to-video",d=>{window.Ve({type:"exported-video",blob:d.blob,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Ve({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||Ba(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",K);window.addEventListener("gesturehold",
K);c.addEventListener("selectstart",K);c.addEventListener("gesturehold",K);window.addEventListener("touchstart",K,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",K,{passive:!1}),c.addEventListener("pointerdown",K)):c.addEventListener("touchstart",K);this.pb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ea,{passive:!1});window.addEventListener("wheel",Ea,{passive:!1});window.addEventListener("resize",
()=>{a:{if(!this.Z){var d=this.ta();var e=this.la();if(this.v.qc()){if(this.vd){if(this.Gd===d&&e<this.Ob){this.vb=this.Ob-e;Ya(this,this.Ob,this.vb);d=void 0;break a}0<this.vb&&(this.vb=0,Ya(this,e,this.vb))}this.Gd=d;this.Ob=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:G.Ya()});this.v.rc()&&(-1!==this.Sa&&clearTimeout(this.Sa),Za(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",
()=>L(this));window.addEventListener("mozfullscreenchange",()=>L(this));window.addEventListener("fullscreenerror",d=>Ra(this,d));window.addEventListener("webkitfullscreenerror",d=>Ra(this,d));window.addEventListener("mozfullscreenerror",d=>Ra(this,d));if(b.rc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;
if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):Ba(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(G.od(!0),L(this)):"exited-fullscreen"===d?(G.od(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Na=new Set;this.Sb=new WeakSet;this.ua=!1}Zc(){window.addEventListener("focus",()=>{k(this,"window-focus",
null,I)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},I);this.pb=0});window.addEventListener("focusin",a=>{a=a.target;(Ca.has(a.tagName.toLowerCase())||Ba(a))&&k(this,"keyboard-blur",null,I)});window.addEventListener("keydown",a=>Sa(this,"keydown",a));window.addEventListener("keyup",a=>Sa(this,"keyup",a));window.addEventListener("dblclick",a=>Ta(this,"dblclick",a,H));window.addEventListener("wheel",
a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.$,pageX:a.pageX,pageY:a.pageY+this.$,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},H)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Ua(a);M(this,"pointerdown",a)}),this.v.ka&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.sb=new self.pe(()=>{M(this,"pointermove",this.La);this.La=null}),this.sb.td=!0,window.addEventListener("pointerrawupdate",
a=>{this.La&&(this.Yb+=this.La.movementX||0,this.Zb+=this.La.movementY||0);this.La=a;a=this.sb;if(-1===a.Ta){var c=Date.now(),d=c-a.Nb,e=a.Oe;d>=e&&a.td?(a.Nb=c,a.ib=!0,a.Ec(),a.ib=!1):a.Ta=self.setTimeout(a.Rd,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Ua(a);Xa(this,"pointerdown",a)}),
window.addEventListener("mousemove",a=>Xa(this,"pointermove",a)),window.addEventListener("mouseup",a=>Xa(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Ua(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.Bc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",
b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.ke()&&!this.v.qc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Ya(this,this.la(),navigator.virtualKeyboard.boundingRect.height)}))}ta(){return this.v.ta()}la(){return this.v.la()}Bc(){var b=[...this.Na];this.Na.clear();if(!this.ua)for(const a of b)(b=a.play())&&b.catch(()=>{this.Sb.has(a)||this.Na.add(a)})}ba(b){if("function"!==
typeof b.play)throw Error("missing play function");this.Sb.delete(b);let a;try{a=b.play()}catch(c){this.Na.add(b);return}a&&a.catch(()=>{this.Sb.has(b)||this.Na.add(b)})}fa(b){this.Na.delete(b);this.Sb.add(b)}Db(b){this.ua=!!b}});"use strict";
async function ra(b){if(b.Ne)throw Error("already initialised");b.Ne=!0;var a=b.bc.xc("dispatchworker.js");b.Hc=await b.bc.kc(a,b.bb,{name:"DispatchWorker"});a=new MessageChannel;b.Mc=a.port1;b.Hc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Tc=await ta(b)}function sa(b){return[b.Mc,b.Tc]}
async function ta(b){const a=b.Dd.length;var c=b.bc.xc("jobworker.js");c=await b.bc.kc(c,b.bb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Hc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Dd.push(c);return e.port1}
self.ne=class{constructor(b){this.bc=b;this.bb=b.ca;this.bb="preview"===b.D?this.bb+"workers/":this.bb+b.cc;this.Qe=Math.min(navigator.hardwareConcurrency||2,16);this.Hc=null;this.Dd=[];this.Tc=this.Mc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Cb({ef:!0,ff:"workermain.js",Ua:["scripts/c3runtime.js"],hc:[],Wc:"",bf:"scripts/",Yc:[],Sd:"html5"}));"use strict";const ab=180/Math.PI;
async function bb(b,a){a.isiOSCordova&&(b.Wb=!0);b.Vc=a.timeScaleMode;b.Jd=["equalpower","HRTF","soundfield"][a.panningModel];b.ud=["linear","inverse","exponential"][a.distanceModel];b.Kd=a.refDistance;b.Id=a.maxDistance;b.Md=a.rolloffFactor;if(b.v.Nc)b.Wb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.wd)});else{var c={latencyHint:a.latencyHint};b.Pd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");cb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&cb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ja=b.g.createGain();b.Ja.connect(b.g.destination);c=a.listenerPos;b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>O(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",
d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function db(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Ed=g;eb(b,g);try{b.na=await fb(b,c,d,e,g,f);if(q){P(b.na,!0);var A=b.na,Y=q.innerAngle,E=q.outerAngle,sb=q.outerGain;if(A.jb){gb(A,q.x,q.y,q.angle);var Ia=self.Va.re;A.F.coneInnerAngle=Ia(Y);A.F.coneOuterAngle=
Ia(E);A.F.coneOuterGain=sb}q.hasOwnProperty("uid")&&(b.na.ma=q.uid)}else P(b.na,!1);b.na.Play(h,m,p,t)}catch(tb){console.error("[Construct] Audio: error starting playback: ",tb);return}finally{c=b.rb.get(g);if(!c)throw Error("expected pending tag");c.Xc--;0===c.Xc&&(c.resolve(),b.rb.delete(g))}r(b)}
async function hb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await ib(b,c);for(const q of Q(b,c)){c=q;var f=d,g=e,h=a;if(!c.Ka){var m=c.N.gain;m.cancelScheduledValues(0);var p=c.s.g.currentTime;g=p+g;m.setValueAtTime(m.value,p);m.linearRampToValueAtTime(f,g);c.Fa=f;c.gb=g;c.Od=h}}R(b)}async function jb(b,a){const c=a.tag;a=a.rate;await ib(b,c);for(const d of Q(b,c))b=d,b.ja!==a&&(b.ja=a,b.Aa())}
async function kb(b,a){const c=a.tag;a=a.pos;await ib(b,c);for(const d of Q(b,c))d.sc(a)}async function lb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await fb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function mb(b,a){if(a=await O(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ha.indexOf(a),-1!==a&&b.ha.splice(a,1)}
async function nb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Yd(b,...e);else if("delay"===c)e=new self.Wd(b,...e);else if("convolution"===c){c=null;try{c=await O(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Vd(b,c.ga,...e);var f=a.bufferType;c.rd=a.bufferOriginalUrl;c.sd=f}else if("flanger"===c)e=new self.Zd(b,...e);else if("phaser"===c)e=new self.ae(b,...e);else if("gain"===c)e=
new self.$d(b,...e);else if("tremolo"===c)e=new self.ce(b,...e);else if("ringmod"===c)e=new self.be(b,...e);else if("distortion"===c)e=new self.Xd(b,...e);else if("compressor"===c)e=new self.Ud(b,...e);else if("analyser"===c)e=new self.Td(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.ia.get(d);e||(e=[],b.ia.set(d,e));a.Bd=e.length;a.da=d;e.push(a);ob(b,d);pb(b)}
async function qb(b,a){const c=a.saveLoadMode;if(3!==c)for(var d of b.L)d.ya()&&1===c||(d.ya()||2!==c)&&d.sa();for(const e of b.ia.values())for(const f of e)f.j();b.ia.clear();b.ec=a.timeScale;b.Jc=a.gameTime;d=a.listenerPos;b.g.listener.setPosition(d[0],d[1],d[2]);b.ua=a.isSilent;b.v.Db(b.ua);b.Rb=a.masterVolume;b.Ja.gain.value=b.Rb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>nb(b,f))));await Promise.all(d);await Promise.all(a.playing.map(e=>rb(b,e,c)));R(b)}
async function ub(b,a){try{const c=b.g.suspend(a.time);b.Ad?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.Ab("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>vb(d)),b.Ad=!0);await c}catch(c){vb(c)}}
function cb(b){b.Kb||(b.Lc=!1,window.addEventListener("pointerup",b.wa,!0),window.addEventListener("touchend",b.wa,!0),window.addEventListener("click",b.wa,!0),window.addEventListener("keydown",b.wa,!0),b.Kb=!0)}
async function O(b,a,c,d,e,f){for(var g of b.ha)if(g.Xa()===c)return await wb(g),g;if(f)return null;if(e&&(b.Wb||b.zd)){f=0;for(let h=0,m=b.ha.length;h<m;++h)g=b.ha[h],b.ha[f]=g,g.ya()?g.j():++f;b.ha.length=f}f="audio/webm; codecs=opus"===d&&!b.Pd;e&&f&&(b.zd=!0);c=!e||b.Wb||f?new self.fe(b,a,c,d,e,f):new self.de(b,a,c,d,e);b.ha.push(c);await wb(c);b.Hd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ea()}),b.Hd.add(a));return c}
function xb(b,a){return(a=b.ia.get(a.toLowerCase()))?a[0].R():b.xa()}function ob(b,a){let c=b.xa();var d=b.ia.get(a);if(d&&d.length){c=d[0].R();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.xa()):e.U(d[f+1].R())}}for(const f of Q(b,a))d=c,e=f.F||f.N,e.disconnect(),e.connect(d);b.Da&&b.Rc===a&&(b.Da.disconnect(),b.Da.connect(c))}function*Q(b,a){if(a)for(const c of b.L)b=c.da,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.na&&!b.na.S()&&(yield b.na)}
function yb(b,a,c){return c?b.v.Me(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function zb(b,a){let c=0;for(let d=0,e=b.L.length;d<e;++d){const f=b.L[d];b.L[c]=f;f.M===a?f.j():++c}b.L.length=c}async function fb(b,a,c,d,e,f){for(const g of b.L)if(g.Xa()===c&&(g.jc()||f))return g.da=e,g;a=await O(b,a,c,d,f);e="html5"===a.Dc?new self.ee(a.s,a,e):new self.ge(a.s,a,e);b.L.push(e);return e}
function eb(b,a){let c=b.rb.get(a);if(!c){let d=null;c={Xc:0,promise:new Promise(e=>d=e),resolve:d};b.rb.set(a,c)}c.Xc++}function ib(b,a){a||(a=b.Ed);return(b=b.rb.get(a))?b.promise:Promise.resolve()}function R(b){if(0<b.Ia.size)r(b);else for(const a of b.L)if(!a.G&&!a.S()){r(b);break}}function Ab(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function pb(b){b.Oc||(b.Oc=!0,Promise.resolve().then(()=>Bb(b)))}
function Bb(b){const a={};for(const [c,d]of b.ia)a[c]=d.map(e=>e.Wa());k(b,"fxstate",{fxstate:a});b.Oc=!1}
async function rb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await fb(b,d,e,f,h,g)}catch(t){console.error("[Construct] Audio: error loading audio state: ",t);return}b=c;(d=a.pan)?(P(b,!0),e=b.F,f=d.pos,b.qa[0]=f[0],b.qa[1]=f[1],b.qa[2]=f[2],f=d.orient,b.pa[0]=f[0],b.pa[1]=f[1],b.pa[2]=f[2],e.setPosition(...b.qa),e.setOrientation(...b.pa),e.coneInnerAngle=d.cia,e.coneOuterAngle=
d.coa,e.coneOuterGain=d.cog,b.ma=d.uid):P(b,!1);c.Play(m,p,q,0);a.isPlaying||c.Za();c.zc(a)}}}function vb(b){console.error("[Audio] Offline rendering error: ",b)}
self.Va=class extends self.lc{constructor(b){super(b,"audio");this.Ja=this.g=null;this.Kb=this.Lc=!1;this.wa=()=>{if(!this.Lc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Kb&&(this.Lc=!0,window.removeEventListener("pointerup",this.wa,!0),window.removeEventListener("touchend",this.wa,!0),window.removeEventListener("click",this.wa,!0),window.removeEventListener("keydown",
this.wa,!0),this.Kb=!1)}};this.ha=[];this.L=[];this.na=null;this.Ed="";this.Hd=new Set;this.Fd=-1;this.rb=new Map;this.Rb=1;this.ua=!1;this.Vc=0;this.ec=1;this.Jc=0;this.Jd="HRTF";this.ud="inverse";this.Kd=600;this.Id=1E4;this.Md=1;this.zd=this.Wb=!1;this.Pd=this.v.le();this.ia=new Map;this.Ia=new Set;this.Ad=this.Oc=!1;this.Rc="";this.Da=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Da&&this.Da.disconnect();this.Rc=c.toLowerCase();this.Da=this.g.createMediaStreamSource(a);this.Da.connect(xb(this,
this.Rc))};this.Ib=null;self.C3Audio_GetOutputStream=()=>{this.Ib||(this.Ib=this.g.createMediaStreamDestination(),this.Ja.connect(this.Ib));return this.Ib.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>bb(this,a)],["play",a=>db(this,a)],["stop",a=>{a=a.tag;for(const c of Q(this,a))c.sa()}],["stop-all",()=>{for(const a of this.L)a.sa()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of Q(this,c))a?d.Za():d.Bb();R(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;
for(const d of Q(this,c))S(d,a)}],["fade-volume",a=>hb(this,a)],["set-master-volume",a=>{this.Rb=a.vol;this.Ja.gain.value=this.Rb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of Q(this,c))Db(d,a)}],["set-silent",a=>{this.ua=a.isSilent;this.v.Db(this.ua);for(const c of this.L)c.Gb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of Q(this,c))d.tc(a)}],["set-playback-rate",a=>jb(this,a)],["seek",a=>kb(this,a)],["preload",a=>lb(this,a)],["unload",a=>mb(this,a)],["unload-all",
()=>{for(const a of this.ha)a.j();this.ha.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.L)c.uc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>nb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.ia.get(a.tag);!a||0>c||c>=a.length||(a[c].aa(d,e,f,g),pb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.ia.get(a);if(c&&c.length){for(const d of c)d.j();this.ia.delete(a);ob(this,
a)}}],["tick",a=>{this.ec=a.timeScale;this.Jc=a.gameTime;this.Fd=a.tickCount;if(0!==this.Vc)for(var c of this.L)c.Aa();(c=a.listenerPos)&&this.g.listener.setPosition(c[0],c[1],c[2]);for(const d of a.instPans){a=d.uid;for(const e of this.L)e.ma===a&&gb(e,d.x,d.y,d.angle)}}],["load-state",a=>qb(this,a)],["offline-render-audio",a=>ub(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}Y(){return this.g}xa(){return this.Ja}zb(){return this.ua}ba(b){this.v.ba(b)}fa(b){this.v.fa(b)}za(){for(var b of this.Ia)b.za();
b=this.g.currentTime;for(var a of this.L)a.za(b);a=this.L.filter(c=>!c.G&&!c.S()).map(c=>c.Wa());k(this,"state",{tickCount:this.Fd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ia].map(c=>({tag:c.da,index:c.Bd,peak:c.Oa,rms:c.Ld,binCount:c.m.frequencyBinCount,freqBins:c.yd}))});0===a.length&&0===this.Ia.size&&ba(this)}static re(b){return b*ab}static dd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static oe(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*
20}};self.Cb.ic(self.Va);"use strict";function wb(b){b.Pb||(b.Pb=b.yc());return b.Pb}self.$c=class{constructor(b,a,c,d,e){this.s=b;this.Se=a;this.Ea=c;this.T=d;this.Pe=e;this.Dc="";this.Pb=null}j(){this.Pb=this.s=null}yc(){}Y(){return this.s.Y()}nc(){return this.Se}Xa(){return this.Ea}mc(){return this.T}ya(){return this.Pe}ea(){}};"use strict";
self.de=class extends self.$c{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Dc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.lb=this.mb=null;this.K.addEventListener("canplaythrough",()=>!0);this.qb=this.Y().createGain();this.ob=null;this.K.addEventListener("canplay",()=>{this.mb&&(this.mb(),this.lb=this.mb=null);!this.ob&&this.K&&(this.ob=this.Y().createMediaElementSource(this.K),this.ob.connect(this.qb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ea}' error: `,f);this.lb&&(this.lb(f),this.lb=this.mb=null)})}j(){zb(this.s,this);this.qb.disconnect();this.qb=null;this.ob.disconnect();this.ob=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.j()}yc(){return new Promise((b,a)=>{this.mb=b;this.lb=a;this.K.src=this.Ea})}P(){return this.K}ea(){return this.K.duration}};"use strict";
async function Eb(b){if(b.Ba)return b.Ba;var a=b.s.v;if("cordova"===a.D&&a.fd(b.Ea)&&a.Mb)b.Ba=await a.yb(b.Ea);else{a=await fetch(b.Ea);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ba=await a.arrayBuffer()}}async function Fb(b){if(b.ga)return b.ga;b.ga=await yb(b.s,b.Ba,b.Re);b.Ba=null}
self.fe=class extends self.$c{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Dc="webaudio";this.ga=this.Ba=null;this.Re=!!f}j(){zb(this.s,this);this.ga=this.Ba=null;super.j()}async yc(){try{await Eb(this),await Fb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ea}': `,b)}}ea(){return this.ga?this.ga.duration:0}};"use strict";let Gb=0;
function P(b,a){a=!!a;b.jb!==a&&(b.jb=a,b.jb?(b.F||(b.F=b.Y().createPanner(),b.F.panningModel=b.s.Jd,b.F.distanceModel=b.s.ud,b.F.refDistance=b.s.Kd,b.F.maxDistance=b.s.Id,b.F.rolloffFactor=b.s.Md),b.N.disconnect(),b.N.connect(b.F),b.F.connect(b.xa())):(b.F.disconnect(),b.N.disconnect(),b.N.connect(b.xa())))}function S(b,a){b.Fa=a;b.N.gain.cancelScheduledValues(0);b.gb=-1;b.N.gain.value=b.oc()}function Db(b,a){a=!!a;b.Ka!==a&&(b.Ka=a,b.Gb())}
function gb(b,a,c,d){b.jb&&(b.qa[0]=a,b.qa[1]=c,b.qa[2]=0,b.pa[0]=Math.cos(d),b.pa[1]=Math.sin(d),b.pa[2]=0,b.F.setPosition(...b.qa),b.F.setOrientation(...b.pa))}function T(b){return b.Qc?b.s.Jc:performance.now()/1E3}
self.ad=class{constructor(b,a,c){this.s=b;this.M=a;this.da=c;this.Hb=Gb++;this.N=this.Y().createGain();this.N.connect(this.xa());this.F=null;this.jb=!1;this.qa=[0,0,0];this.pa=[0,0,0];this.G=!0;this.X=this.ra=this.I=!1;this.Fa=1;this.Ka=!1;this.ja=1;b=this.s.Vc;this.Qc=1===b&&!this.ya()||2===b;this.gb=this.ma=-1;this.Od=!1}j(){this.M=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.N.disconnect();this.N=null}Y(){return this.s.Y()}xa(){return xb(this.s,this.da)}nc(){return this.M.nc()}Xa(){return this.M.Xa()}mc(){return this.M.mc()}ya(){return this.M.ya()}S(){}jc(){}IsPlaying(){return!this.G&&
!this.I&&!this.S()}Ga(){}ea(){return this.M.ea()}Play(){}sa(){}Za(){}Bb(){}za(b){-1!==this.gb&&b>=this.gb&&(this.gb=-1,this.Od&&this.sa(),Ab(this.s,"fade-ended",this.da,this.Hb))}oc(){const b=this.Fa;return isFinite(b)?b:0}zb(){return this.s.zb()}Gb(){}tc(){}Aa(){}sc(){}uc(){}pc(){}Wa(){var b=this.Hb,a=this.da,c=this.ea(),d=this.Fa,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.qa,orient:this.pa,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ma}}else f=null;return{aiid:b,
tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ga(),playbackRate:this.ja,uid:this.ma,bufferOriginalUrl:this.nc(),bufferUrl:"",bufferType:this.mc(),isMusic:this.ya(),isLooping:this.X,isMuted:this.Ka,resumePosition:this.pc(),pan:f}}zc(b){var a=b.playbackRate;this.ja!==a&&(this.ja=a,this.Aa());Db(this,b.isMuted)}};"use strict";
self.ee=class extends self.ad{constructor(b,a,c){super(b,a,c);this.M.qb.connect(this.N);this.M.onended=()=>this.Ac()}j(){this.sa();this.M.qb.disconnect();super.j()}P(){return this.M.P()}Ac(){this.G=!0;this.ma=-1;Ab(this.s,"ended",this.da,this.Hb)}S(){return this.P().ended}jc(){return this.G?!0:this.S()}Ga(){let b=this.P().currentTime;this.X||(b=Math.min(b,this.ea()));return b}Play(b,a,c){const d=this.P();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);S(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.M.Xa()}' to position '${c}': `,e)}this.s.ba(d);this.I=this.G=!1;this.X=b;this.ja=1}sa(){const b=this.P();b.paused||b.pause();this.s.fa(b);this.G=!0;this.I=!1;this.ma=-1}Za(){if(!(this.I||this.G||this.S())){var b=this.P();b.paused||b.pause();this.s.fa(b);this.I=!0}}Bb(){!this.I||this.G||this.S()||(this.s.ba(this.P()),this.I=!1)}Gb(){this.P().muted=this.Ka||this.zb()}tc(b){b=!!b;this.X!==b&&(this.X=
b,this.P().loop=b)}Aa(){let b=this.ja;this.Qc&&(b*=this.s.ec);try{this.P().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}sc(b){if(!this.G&&!this.S())try{this.P().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}pc(){return this.Ga()}uc(b){b?this.IsPlaying()?(this.P().pause(),this.ra=!0):this.ra=!1:this.ra&&(this.s.ba(this.P()),this.ra=!1)}};"use strict";function U(b){b.o&&b.o.disconnect();b.o=null;b.$a=null}
self.ge=class extends self.ad{constructor(b,a,c){super(b,a,c);this.o=null;this.Ub=d=>this.Ac(d);this.Kc=!0;this.$a=null;this.O=this.Vb=this.Xb=0;this.Sc=1}j(){this.sa();U(this);this.Ub=null;super.j()}Ac(b){this.I||this.ra||b.target!==this.$a||(this.G=this.Kc=!0,this.ma=-1,U(this),Ab(this.s,"ended",this.da,this.Hb))}S(){return!this.G&&this.o&&this.o.loop||this.I?!1:this.Kc}jc(){return!this.o||this.G?!0:this.S()}Ga(){let b;b=this.I?this.O:this.Vb+(T(this)-this.Xb)*this.ja;this.X||(b=Math.min(b,this.ea()));
return b}Play(b,a,c,d){this.Sc=1;S(this,a);U(this);this.o=this.Y().createBufferSource();this.o.buffer=this.M.ga;this.o.connect(this.N);this.$a=this.o;this.o.onended=this.Ub;this.o.loop=b;this.o.start(d,c);this.I=this.G=this.Kc=!1;this.X=b;this.ja=1;this.Xb=T(this);this.Vb=c}sa(){if(this.o)try{this.o.stop(0)}catch(b){}this.G=!0;this.I=!1;this.ma=-1}Za(){this.I||this.G||this.S()||(this.O=this.Ga(),this.X&&(this.O%=this.ea()),this.I=!0,this.o.stop(0))}Bb(){!this.I||this.G||this.S()||(U(this),this.o=
this.Y().createBufferSource(),this.o.buffer=this.M.ga,this.o.connect(this.N),this.$a=this.o,this.o.onended=this.Ub,this.o.loop=this.X,S(this,this.Fa),this.Aa(),this.o.start(0,this.O),this.Xb=T(this),this.Vb=this.O,this.I=!1)}oc(){return super.oc()*this.Sc}Gb(){this.Sc=this.Ka||this.zb()?0:1;S(this,this.Fa)}tc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}Aa(){let b=this.ja;this.Qc&&(b*=this.s.ec);this.o&&(this.o.playbackRate.value=b)}sc(b){this.G||this.S()||(this.I?this.O=b:(this.Za(),this.O=
b,this.Bb()))}pc(){return this.O}uc(b){b?this.IsPlaying()?(this.ra=!0,this.O=this.Ga(),this.X&&(this.O%=this.ea()),this.o.stop(0)):this.ra=!1:this.ra&&(U(this),this.o=this.Y().createBufferSource(),this.o.buffer=this.M.ga,this.o.connect(this.N),this.$a=this.o,this.o.onended=this.Ub,this.o.loop=this.X,S(this,this.Fa),this.Aa(),this.o.start(0,this.O),this.Xb=T(this),this.Vb=this.O,this.ra=!1)}zc(b){super.zc(b);this.O=b.resumePosition}};"use strict";function V(b){return b.g.createGain()}
function W(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class X{constructor(b){this.s=b;this.g=b.Y();this.Bd=-1;this.T=this.da="";this.l=null}j(){this.g=null}R(){}U(){}Wa(){return{type:this.T,tag:this.da,params:this.l}}}
self.Yd=class extends X{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.l=[a,c,d,e,f,g];this.u=V(this);this.i=V(this);this.i.gain.value=g;this.h=V(this);this.h.gain.value=1-g;this.B=this.g.createBiquadFilter();this.B.type=a;this.B.frequency.value=c;this.B.detune.value=d;this.B.Q.value=e;this.B.gain.vlaue=f;this.u.connect(this.B);this.u.connect(this.h);this.B.connect(this.i)}j(){this.u.disconnect();this.B.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 1:this.l[1]=a;W(this,this.B.frequency,a,c,d);break;case 2:this.l[2]=a;W(this,this.B.detune,a,c,d);break;case 3:this.l[3]=a;W(this,this.B.Q,a,c,d);break;case 4:this.l[4]=a,W(this,this.B.gain,a,c,d)}}};
self.Wd=class extends X{constructor(b,a,c,d){super(b);this.T="delay";this.l=[a,c,d];this.u=V(this);this.i=V(this);this.i.gain.value=d;this.h=V(this);this.h.gain.value=1-d;this.nb=V(this);this.V=this.g.createDelay(a);this.V.delayTime.value=a;this.fb=V(this);this.fb.gain.value=c;this.u.connect(this.nb);this.u.connect(this.h);this.nb.connect(this.i);this.nb.connect(this.V);this.V.connect(this.fb);this.fb.connect(this.nb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.nb.disconnect();
this.V.disconnect();this.fb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}aa(b,a,c,d){const e=self.Va.dd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[2]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 4:this.l[1]=e(a);W(this,this.fb.gain,e(a),c,d);break;case 5:this.l[0]=a,W(this,this.V.delayTime,a,c,d)}}};
self.Vd=class extends X{constructor(b,a,c,d){super(b);this.T="convolution";this.l=[c,d];this.sd=this.rd="";this.u=V(this);this.i=V(this);this.i.gain.value=d;this.h=V(this);this.h.gain.value=1-d;this.eb=this.g.createConvolver();this.eb.normalize=c;this.eb.buffer=a;this.u.connect(this.eb);this.u.connect(this.h);this.eb.connect(this.i)}j(){this.u.disconnect();this.eb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}aa(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[1]=a,W(this,this.i.gain,a,c,d),W(this,this.h.gain,1-a,c,d)}}Wa(){const b=super.Wa();b.bufferOriginalUrl=this.rd;b.bufferUrl="";b.bufferType=this.sd;return b}};
self.Zd=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.l=[a,c,d,e,f];this.u=V(this);this.h=V(this);this.h.gain.value=1-f/2;this.i=V(this);this.i.gain.value=f/2;this.hb=V(this);this.hb.gain.value=e;this.V=this.g.createDelay(a+c);this.V.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.J=V(this);this.J.gain.value=c;this.u.connect(this.V);this.u.connect(this.h);this.V.connect(this.i);this.V.connect(this.hb);this.hb.connect(this.V);this.A.connect(this.J);
this.J.connect(this.V.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.V.disconnect();this.A.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();this.hb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[4]=a;W(this,this.i.gain,a/2,c,d);W(this,this.h.gain,1-a/2,c,d);break;case 6:this.l[1]=a/1E3;W(this,this.J.gain,a/1E3,
c,d);break;case 7:this.l[2]=a;W(this,this.A.frequency,a,c,d);break;case 8:this.l[3]=a/100,W(this,this.hb.gain,a/100,c,d)}}};
self.ae=class extends X{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.l=[a,c,d,e,f,g];this.u=V(this);this.h=V(this);this.h.gain.value=1-g/2;this.i=V(this);this.i.gain.value=g/2;this.B=this.g.createBiquadFilter();this.B.type="allpass";this.B.frequency.value=a;this.B.detune.value=c;this.B.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.J=V(this);this.J.gain.value=e;this.u.connect(this.B);this.u.connect(this.h);this.B.connect(this.i);this.A.connect(this.J);this.J.connect(this.B.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.B.disconnect();this.A.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;W(this,this.i.gain,a/2,c,d);W(this,this.h.gain,1-a/2,c,d);break;case 1:this.l[0]=a;W(this,this.B.frequency,a,c,d);break;case 2:this.l[1]=a;W(this,this.B.detune,a,c,
d);break;case 3:this.l[2]=a;W(this,this.B.Q,a,c,d);break;case 6:this.l[3]=a;W(this,this.J.gain,a,c,d);break;case 7:this.l[4]=a,W(this,this.A.frequency,a,c,d)}}};self.$d=class extends X{constructor(b,a){super(b);this.T="gain";this.l=[a];this.m=V(this);this.m.gain.value=a}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}aa(b,a,c,d){const e=self.Va.dd;switch(b){case 4:this.l[0]=e(a),W(this,this.m.gain,e(a),c,d)}}};
self.ce=class extends X{constructor(b,a,c){super(b);this.T="tremolo";this.l=[a,c];this.m=V(this);this.m.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.J=V(this);this.J.gain.value=c/2;this.A.connect(this.J);this.J.connect(this.m.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.J.disconnect();this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=
a;W(this,this.m.gain,1-a/2,c,d);W(this,this.J.gain,a/2,c,d);break;case 7:this.l[0]=a,W(this,this.A.frequency,a,c,d)}}};
self.be=class extends X{constructor(b,a,c){super(b);this.T="ringmod";this.l=[a,c];this.u=V(this);this.i=V(this);this.i.gain.value=c;this.h=V(this);this.h.gain.value=1-c;this.ub=V(this);this.ub.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.ub.gain);this.A.start(0);this.u.connect(this.ub);this.u.connect(this.h);this.ub.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.ub.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=a;W(this,this.i.gain,a,c,d);W(this,this.h.gain,1-a,c,d);break;case 7:this.l[0]=a,W(this,this.A.frequency,a,c,d)}}};
self.Xd=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.l=[a,c,d,e,f];this.u=V(this);this.ac=V(this);this.$b=V(this);b=d;.01>b&&(b=.01);this.ac.gain.value=b;this.$b.gain.value=Math.pow(1/b,.6)*e;this.i=V(this);this.i.gain.value=f;this.h=V(this);this.h.gain.value=1-f;this.fc=this.g.createWaveShaper();this.Fc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Fc[32768+e]=f,this.Fc[32768-
e-1]=-f;this.fc.curve=this.Fc;this.u.connect(this.ac);this.u.connect(this.h);this.ac.connect(this.fc);this.fc.connect(this.$b);this.$b.connect(this.i)}j(){this.u.disconnect();this.ac.disconnect();this.fc.disconnect();this.$b.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[4]=a,W(this,this.i.gain,a,c,d),W(this,this.h.gain,
1-a,c,d)}}};self.Ud=class extends X{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.l=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}aa(){}};
self.Td=class extends X{constructor(b,a,c){super(b);this.T="analyser";this.l=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.yd=new Float32Array(this.m.frequencyBinCount);this.Nd=new Uint8Array(a);this.Ld=this.Oa=0;b=this.s;b.Ia.add(this);R(b)}j(){this.s.Ia.delete(this);this.m.disconnect();super.j()}za(){this.m.getFloatFrequencyData(this.yd);this.m.getByteTimeDomainData(this.Nd);const b=this.m.fftSize;let a=this.Oa=0;for(var c=0;c<b;++c){let d=(this.Nd[c]-
128)/128;0>d&&(d=-d);this.Oa<d&&(this.Oa=d);a+=d*d}c=self.Va.oe;this.Oa=c(this.Oa);this.Ld=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}aa(){}};"use strict";
async function Hb(b,a){b.Pc=a.isInWorker;a=document.createElement("video");b.dc=!!a.requestVideoFrameCallback&&!b.v.qc();const c=!!self.createImageBitmap;b.tb=b.Pc||c;return{postImageBitmaps:b.tb,supportedFormats:{"video/webm":!!a.canPlayType("video/webm"),"video/ogg":!!a.canPlayType("video/ogg"),"video/mp4":!!a.canPlayType("video/mp4")}}}
async function Ib(b,a){if(!b.Gc.has(a)){a.c3_rvfcId=a.requestVideoFrameCallback(()=>Ib(b,a));try{const c=a.c3_sequenceNumber++,d=await createImageBitmap(a);c>a.c3_lastFrameSequence&&(a.c3_imageBitmap=d,a.c3_lastFrameSequence=c)}catch(c){}}}function Z(b,a,c,d){b.Gc.has(a)||u(b,"playback-event",c,{type:d})}
self.Cb.ic(class extends self.ie{constructor(b){super(b);this.tb=this.dc=this.Pc=this.ab=!1;this.Tb=this.Ue=0;this.Gc=new WeakSet;n(this,"init",a=>Hb(this,a));v(this,"play",a=>{this.ba(a)});v(this,"pause",a=>{this.fa(a);a.pause()});v(this,"set-source",(a,c)=>{a.src=c.src;a.load()});v(this,"set-playback-time",(a,c)=>{try{a.currentTime=c.time}catch(d){console.error("[Video] Exception setting playback time: ",d)}});v(this,"set-playback-rate",(a,c)=>{try{a.playbackRate=c.rate}catch(d){console.error("[Video] Exception setting playback rate: ",
d)}});v(this,"set-looping",(a,c)=>{a.loop=c.isLooping});v(this,"set-muted",(a,c)=>{a.muted=c.isMuted});v(this,"set-volume",(a,c)=>{a.volume=c.volume});self.C3Video_GetElement=a=>this.W.get(a)}ba(b){this.v.ba(b);this.tb&&this.dc&&-1===b.c3_rvfcId&&(b.c3_rvfcId=b.requestVideoFrameCallback(()=>Ib(this,b)))}fa(b){this.v.fa(b);this.tb&&this.dc&&-1!==b.c3_rvfcId&&(b.cancelVideoFrameCallback(b.c3_rvfcId),b.c3_rvfcId=-1)}cd(b,a){const c=document.createElement("video");c.crossOrigin="anonymous";c.playsInline=
!0;c.c3_imageBitmap=null;c.c3_rvfcId=-1;c.c3_sequenceNumber=0;c.c3_lastFrameSequence=-1;c.addEventListener("canplay",()=>Z(this,c,b,0));c.addEventListener("canplaythrough",()=>Z(this,c,b,1));c.addEventListener("ended",()=>Z(this,c,b,2));c.addEventListener("error",()=>Z(this,c,b,3));c.addEventListener("loadstart",()=>Z(this,c,b,4));c.addEventListener("playing",()=>Z(this,c,b,5));c.addEventListener("pause",()=>Z(this,c,b,6));c.addEventListener("stalled",()=>Z(this,c,b,7));const d=a.autoplay;0===d?(c.autoplay=
!1,c.preload="none"):1===d?(c.autoplay=!1,c.preload="auto"):c.autoplay=!0;a.src&&(c.src=a.src);2===d&&this.ba(c);this.Tb++;r(this);return c}hd(){}ed(b){this.fa(b);b&&!b.paused&&!b.ended&&0<b.currentTime&&b.pause();b.src="";this.Tb=Math.max(this.Tb-1,0);0===this.Tb&&ba(this);this.Gc.add(b)}za(){const b={},a={sequenceNumber:this.Ue++,videoData:b},c=[],d=[];for(const [e,f]of this.W.entries()){const g={currentTime:f.currentTime,playbackRate:f.playbackRate,duration:f.duration,videoWidth:f.videoWidth,videoHeight:f.videoHeight};
if(this.tb)if(this.dc){const h=f.c3_imageBitmap;f.c3_imageBitmap=null;(g.imageBitmap=h)&&c.push(h)}else d.push(createImageBitmap(f).then(h=>{g.imageBitmap=h;c.push(h)}).catch(()=>{g.imageBitmap=null}));b[e.toString()]=g}Promise.all(d).then(()=>{this.Pc?k(this,"state",a,!1,c):l(this,"state",a)})}});
